blank_issues_enabled: false
contact_links:
  - name: Report Protocol Bug
    url: https://github.com/paritytech/dotns/issues/new?template=bug_report.md
    about: For bugs in the DotNS protocol or contracts, report on the main repository.

  - name: Feature Request
    url: https://github.com/paritytech/dotns/issues/new?template=feature_request.md
    about: For protocol feature requests, submit to the main repository.

  - name: Discussions
    url: https://github.com/paritytech/dotns/discussions
    about: Questions and general discussion.